### ISSUE TITLE
Out of Memory When Compiling Angular with `aot`

### ISSUE THREAD

**Issue by snow-swallow** [timelyxyz/blog#16]
>Angular CLI: 1.7.4
Node: 8.10.0
Angular: 5.2.10
OS: darwin x64

**Issue Description**
The build/serve with aot would probably failed. However, it works if I remove the aot/prod param.
Here's my error log.
```shell
92% chunk asset optimization
<--- Last few GCs --->

[93700:0x102801e00]   145215 ms: Mark-sweep 1342.7 (1467.7) -> 1342.7 (1469.7) MB, 855.7 / 0.0 ms  allocation failure GC in old space requested
[93700:0x102801e00]   146103 ms: Mark-sweep 1342.7 (1469.7) -> 1342.5 (1437.2) MB, 887.1 / 0.0 ms  last resort GC in old space requested
[93700:0x102801e00]   146951 ms: Mark-sweep 1342.5 (1437.2) -> 1342.5 (1435.7) MB, 847.6 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x7459c0257c1 <JSObject>
    1: /* anonymous */ [/Users/xxx/web-app/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:~342] [pc=0x2284d747912e](this=0x7453720c211 <JSGlobal Object>,chunk=0x745500bede9 <String[6]: $event>,original=0x745616556a1 <Object map = 0x74532790011>)
    2: SourceNode_walk [/Users/xxx/web-app/n...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewUninitializedFixedArray(int) [/usr/local/bin/node]
 5: v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::GrowCapacity(v8::internal::Handle<v8::internal::JSObject>, unsigned int)[/usr/local/bin/node]
 6: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x2284d5f842fd
```

**Reason**
hmmm, it seems to be an known issue of Node.js when has already been fixed on later version like 8.x. 

**Solution**
Add `max_old_space_size` to expand the max memory size. So just replace the build command `ng build` with `node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build`.

**Reference**
> https://github.com/angular/angular-cli/issues/5618
https://github.com/angular/angular-cli/issues/1652

**Comment by prudhvichitturi** [comment]
This has been changed in angular 7 now. I couldn't able to find the path of ng.. Please any help for finding its path in node modules..

`> node --max_old_space_size=5048 ng build --prod --aot --source-map=false

module.js:540
    throw err;
    ^

Error: Error: Cannot find module '/Users/work/ui/node_modules/@angular/cli/bin/ng'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! data-ui@1.0.0 build-script-a7: `node --max_old_space_size=5048 ng build --prod --aot --source-map=false`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the data-ui@1.0.0 build-script-a7 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.npm/_logs/2019-01-28T08_13_45_344Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! data-ui@1.0.0 build: `npm run config -- --environment=prod && npm run build-script-a7 && npm run prod-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the data-ui@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.npm/_logs/2019-01-28T08_13_45_364Z-debug.log`
